name: "regression"
backend: "onnxruntime"
max_batch_size: 32

dynamic_batching {
  preferred_batch_size: [8, 16]
  max_queue_delay_microseconds: 1000
}

instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]